{"id": 2105, "title": "Ticket #2105: Shadow will treat closed socket as an error after claim is deactivated", "description": "<blockquote>\nWhen a job completes and the shadow deactivates the claim.  If the shadow then fails to notify the schedd of claim deactivation, it will set a timer to try the notify again later, then return the the daemon core pump.\n\n<p>The shadow will then try and read from the socket to the execute machine and treat the fact that the socket has been closed as an error.  Thus when the submit machine is loaded, and the schedd is slow to respond to shadow notifications, some jobs will be run again even when they completed successfully.\n\n</p><p>The job log will show\n\n</p><p></p><div class=\"code\">\n<pre class=\"code\">022 (086.799.000) 04/27 12:39:03 Job disconnected, attempting to reconnect\n    Socket between submit and execute hosts closed unexpectedly\n    Trying to reconnect to slot7@e080.chtc.wisc.edu &lt;128.104.58.90:59182&gt;\n...\n024 (086.799.000) 04/27 12:39:04 Job reconnection failed\n    Job not found at execution machine\n    Can not reconnect to slot7@e080.chtc.wisc.edu, rescheduling job\n</pre></div>\n\n\n<p>While the logs on the execute machine will show that the job completed successfully and the claim was deactivated normally.\n\n</p><p>The fix is for the the shadow to NOT treat the closed socked as an error if the claim has been deactivated.</p></blockquote>", "remarks": "<blockquote>\n<em>2011-Nov-22 13:38:47 by tannenba:</em> <br/>\n\n<strong>CODE REVIEW</strong>\n\n<p>was performed by tannenba.</p></blockquote>", "derived_tickets": "", "attachments": "<blockquote>\n<ul>\n<li><a href=\"attach_get/334/2105.diff\">2105.diff</a>\n3096 bytes added by johnkn on 2011-Apr-27 22:03:51 UTC.\n<br/>\nadds a method in the remote resource class to access the claim deactivated flags, and uses that method in baseshadow to test for claim deactivation when the socket read fails. This patch also adds a test param SHADOW_TEST_JOB_CLEANUP_RETRY which will force the condition that causes this bug to be triggered. \n<br/>\n</li></ul>\n</blockquote>", "check_ins": "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody><tr><td align=\"right\" valign=\"top\" width=\"160\">2011-Apr-28 10:52</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"chngview?cn=21615\">[21615]</a></span>: ===GT=== <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=2105\" onclick=\"get_ticket_and_populate_wrapper('2105'); return false;\" title=\"Shadow will treat closed socket as an error after claim is deactivated\">#2105</a></span> ===VersionHistory=== Fixed bug in the shadow where it would treat the closed socket to the execute machine as an error after it had asked for the claim to be deactivated and the SCHEDD was busy. So a busy SCHEDD could result in the job being re-run.  (By John (TJ) Knoeller )</td></tr>\n</tbody></table>", "type": "defect", "last_change": "2011-Nov-22 13:38", "status": "resolved", "created": "2011-Apr-27 14:36", "fixed_version": "2011-Apr-27 14:36", "broken_version": "v070505", "priority": "2", "subsystem": "Daemons", "assigned_to": "johnkn", "derived_from": "", "creator": "johnkn", "rust": "", "customer_group": "support", "visibility": "public", "notify": "tstclair@redhat.com", "due_date": ""}