{"id": 2131, "title": "Ticket #2131: CCB reconnect crashes if socket creation fails", "description": "<blockquote>\nThe following crash of the master was observed on a test machine at ANI when the network was down:\n\n<p></p><div class=\"verbatim\">\n<pre>04/19/11 19:28:30 Calling Timer handler 7842 (CCBListener::ReconnectTime)\n04/19/11 19:28:40 ERROR \"Assertion ERROR on (sock)\" at line 548 in file /home/condor/execute/dir_12455/userdir/src/condor_daemon_client/daemon.cpp\n</pre></div>\n</blockquote>", "remarks": "<blockquote>\n</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody><tr><td align=\"right\" valign=\"top\" width=\"160\">2011-May-05 17:28</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"chngview?cn=21798\">[21798]</a></span>: Fixed a crash in CCB when reconnecting during a network outage. ===GT=== <span class=\"ticket\"><a class=\"resolved\" href=\"tktview?tn=2131\" title=\"CCB reconnect crashes if socket creation fails\">#2131</a></span> ===VersionHistory=== Fixed a problem that could cause Condor daemons to crash when reconnecting to CCB during a network outage.  (By Dan Bradley )</td></tr>\n</tbody></table>", "type": "defect", "last_change": "2011-May-05 17:31", "status": "resolved", "created": "2011-May-05 17:24", "fixed_version": "2011-May-05 17:24", "broken_version": "v070400", "priority": "4", "subsystem": "", "assigned_to": "danb", "derived_from": "", "creator": "danb", "rust": "", "customer_group": "cms", "visibility": "public", "notify": "", "due_date": ""}