{"id": 1741, "title": "Ticket #1741: detect error/except loops and break them", "description": "<blockquote>\nPete and I were just discussing exceptions in DAGMan, and the possibility that things could get into a state where DAGMan excepts, gets re-started, goes into recovery mode, and excepts again because of the problem that caused the original exception.  Right now, if that happens, the loop will never be broken without manual action from a user.\n\n<p>I don't think we've seen this very often, but it's certainly possible.  At any rate, we were thinking that we could do something, maybe with periodic_hold, to detect such loops and break them after some configurable number of times.</p></blockquote>", "remarks": "<blockquote>\n</blockquote>", "derived_tickets": "", "attachments": "<html><head></head><body></body></html>", "check_ins": "", "type": "enhance", "last_change": "2010-Oct-28 10:27", "status": "new", "created": "2010-Oct-28 10:27", "fixed_version": "2010-Oct-28 10:27", "broken_version": "v070504", "priority": "4", "subsystem": "Dag", "assigned_to": "", "derived_from": "", "creator": "wenger", "rust": "", "customer_group": "other", "visibility": "public", "notify": "wenger@cs.wisc.edu,psilord@cs.wisc.edu", "due_date": ""}