{"id": 215, "title": "Ticket #215: Add a nightly test that tests DAG recovery", "description": "<blockquote>\nWe should have a test that tests DAG recovery -- I need to figure out how to fit this into the test setup, though.\n\n<p>See job_dagman_retry_recovery -- this isn't quite working yet.</p></blockquote>", "remarks": "<blockquote>\njob_dagman_retry.run causes a dag to fail and drop a rescue dag. It then clears the issue that made the node fails and it then reruns via the rescue dag. Is this sufficient? bt\n\n<p>No, a rescue DAG is totally separate from recovery mode.  wenger 2009-05-27\n\n</p><p>Made this test a while ago, just made changes that should fix the failures on MacOS.  wenger 2009-06-23.</p></blockquote>", "derived_tickets": "", "attachments": "<html><head></head><body></body></html>", "check_ins": "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody><tr><td align=\"right\" valign=\"top\" width=\"160\">2021-Sep-29 14:47</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/f4f5ef831b45e56e98d1935d430bff08a7240f6e\">[64524]</a></span>: Merged <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/e78823ffde512c9c225c3d38d02490f8ce69d4b6\">[64396]</a></span>, <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/7047e4fad4fc77b8a32df85200ece20d70058e9e\">[64400]</a></span>, <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/47afa5a5de6aab78738faa1be2b7ac002df4ef15\">[64403]</a></span>, <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/4b5ebcbbf80f08b460ed80167f6c972da3a0dbaf\">[64404]</a></span>, <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/ea44730b66ad691d3c0b1a40e2c3131bac50c6f2\">[64409]</a></span>, <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/b86002d6f23b9762281f401a6245189c84ee3a25\">[64419]</a></span>, <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/ed704bfa2281a78bf33b3761f158cf30d084c0a7\">[64430]</a></span>, <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/3b3b30eeb2893625a99b8382807cfe07d5694c56\">[64454]</a></span>, <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/98863c7fc01f43873340e4d8cc818f3b5e3e7714\">[64455]</a></span>, <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/950c7fba4ce7659e640129c948cb8c2920305ff5\">[64509]</a></span>, <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/ed37b96e73a2469483a08990651176852730af19\">[64523]</a></span>, Merge pull request <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=215\" onclick=\"get_ticket_and_populate_wrapper('215'); return false;\" title=\"Add a nightly test that tests DAG recovery\">#215</a></span> from htcondor/V9_3-HTCONDOR-741-file-transfer-last-run-counts Added version history (HTCONDOR-741) Committer: <span class=\"wiki\"><a class=\"missing\" href=\"wiki?p=GitHub\" title=\"Git Hub\">GitHub</a></span>  (By Tim Theisen )</td></tr>\n<tr><td align=\"right\" valign=\"top\" width=\"160\">2009-Jun-23 11:21</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/b14520137d9415a6194c8d72c05385da8040fac1\">[24850]</a></span>: Made a change that should fix the job_dagman_retry_recovery failures on MacOS -- now, when DAGMan checks at startup for a conflicting DAGMan running on the same DAG, it continues rather than exiting if it's not sure whether the DAGMan that wrote the lock file is alive. (See gittrac <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=215\" onclick=\"get_ticket_and_populate_wrapper('215'); return false;\" title=\"Add a nightly test that tests DAG recovery\">#215</a></span>, <span class=\"ticket\"><a class=\"stalled\" href=\"/tickets?ticket=587\" onclick=\"get_ticket_and_populate_wrapper('587'); return false;\" title=\"Possibly allow elimination of ProcessId sleep at DAGMan startup\">#587</a></span>.)  (By Kent Wenger )</td></tr>\n<tr><td align=\"right\" valign=\"top\" width=\"160\">2009-Jun-23 11:21</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/780dc5bad411c8f9fc8d7b1b15cb054ffc7dd3d0\">[14946]</a></span>: Made a change that should fix the job_dagman_retry_recovery failures on MacOS -- now, when DAGMan checks at startup for a conflicting DAGMan running on the same DAG, it continues rather than exiting if it's not sure whether the DAGMan that wrote the lock file is alive. (See gittrac <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=215\" onclick=\"get_ticket_and_populate_wrapper('215'); return false;\" title=\"Add a nightly test that tests DAG recovery\">#215</a></span>, <span class=\"ticket\"><a class=\"stalled\" href=\"/tickets?ticket=587\" onclick=\"get_ticket_and_populate_wrapper('587'); return false;\" title=\"Possibly allow elimination of ProcessId sleep at DAGMan startup\">#587</a></span>.)  (By Kent Wenger )</td></tr>\n</tbody></table>", "type": "enhance", "last_change": "2010-Jan-31 13:57", "status": "resolved", "created": "2009-Feb-16 11:54", "fixed_version": "2009-Feb-16 11:54", "broken_version": "", "priority": "4", "subsystem": "Dag", "assigned_to": "wenger", "derived_from": "", "creator": "wenger", "rust": "", "customer_group": "other", "visibility": "public", "notify": "", "due_date": ""}