{"id": 2234, "title": "Ticket #2234: condor_router_history doesn't handle exception for bad option", "description": "<blockquote>\nWhen a bad option is given to condor_router_history, it doesn't handle it gracefully:\n\n<p></p><div class=\"code\">\n<pre class=\"code\">$ condor_router_history --xxx\nTraceback (most recent call last):\n  File \"/usr/local/condor/bin/condor_router_history\", line 129, in &lt;module&gt;\n    options,args = getopt.getopt(sys.argv[1:],\"h\",long_options)\n  File \"/usr/lib64/python2.6/getopt.py\", line 89, in getopt\n    opts, args = do_longs(opts, args[0][2:], longopts, args[1:])\n  File \"/usr/lib64/python2.6/getopt.py\", line 153, in do_longs\n    has_arg, opt = long_has_args(opt, longopts)\n  File \"/usr/lib64/python2.6/getopt.py\", line 170, in long_has_args\n    raise GetoptError('option --%s not recognized' % opt, opt)\ngetopt.GetoptError: option --xxx not recognized\n</pre></div>\n</blockquote>", "remarks": "<blockquote>\n<em>2011-Jun-13 17:02:30 by eje:</em> <br/>\n\nrepro/test:\n\n<p>before fix, bad options yield a stack trace:\n</p><div class=\"code\">\n<pre class=\"code\">$ condor_router_history --xxx\nTraceback (most recent call last):\n  File \"/usr/local/condor/bin/condor_router_history\", line 129, in &lt;module&gt;\n    options,args = getopt.getopt(sys.argv[1:],\"h\",long_options)\n  File \"/usr/lib64/python2.6/getopt.py\", line 89, in getopt\n    opts, args = do_longs(opts, args[0][2:], longopts, args[1:])\n  File \"/usr/lib64/python2.6/getopt.py\", line 153, in do_longs\n    has_arg, opt = long_has_args(opt, longopts)\n  File \"/usr/lib64/python2.6/getopt.py\", line 170, in long_has_args\n    raise GetoptError('option --%s not recognized' % opt, opt)\ngetopt.GetoptError: option --xxx not recognized\n</pre></div>\n\n\n<p>after fix, bad options yield error message with usage:\n</p><div class=\"code\">\n<pre class=\"code\">$ condor_router_history --xxx\nCommand line argument error: option --xxx not recognized\n\nUSAGE: condor_router_history [OPTIONS]\n --show_records             (show individual records in addition to summary)\n --show_iwd                 (when showing records, include working directory)\n --age=&lt;days&gt;               (how many days ago end time should be)\n --days=&lt;days&gt;              (how many days report should cover)\n --start=\"YYYY-MM-DD HH:MM\" (date of start time of report)\n\n\n$ condor_router_history --age=xxx\nCommand line argument error: invalid literal for float(): xxx\n\nUSAGE: condor_router_history [OPTIONS]\n --show_records             (show individual records in addition to summary)\n --show_iwd                 (when showing records, include working directory)\n --age=&lt;days&gt;               (how many days ago end time should be)\n --days=&lt;days&gt;              (how many days report should cover)\n --start=\"YYYY-MM-DD HH:MM\" (date of start time of report)\n\n</pre></div>\n\n\n<p></p><hr/>\n<em>2011-Jun-13 18:00:53 by eje:</em> <br/>\n\nThis bug depends on <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=2226\" onclick=\"get_ticket_and_populate_wrapper('2226'); return false;\" title=\"condor_router_ scripts incorrect in 7_6 series\">#2226</a></span>\n\n<p></p><hr/>\n<em>2011-Jun-27 10:54:36 by danb:</em> <br/>\n\nPatch looks good.  Thanks.</blockquote>", "derived_tickets": "", "attachments": "<html><head></head><body><blockquote>\n<ul>\n<li><a href=\"../files/375/gt2234-router-history-except\">gt2234-router-history-except</a>\n2194 bytes added by eje on 2011-Jun-13 21:56:56 UTC.\n<br/>\nAdds try/except around argument handling<br/>\n</li></ul>\n</blockquote></body></html>", "check_ins": "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody><tr><td align=\"right\" valign=\"top\" width=\"160\">2011-Jun-27 14:23</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"chngview?cn=22302\">[22302]</a></span>: === GT <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=2234\" onclick=\"get_ticket_and_populate_wrapper('2234'); return false;\" title=\"condor_router_history doesn't handle exception for bad option\">#2234</a></span> === Patch created by eje Fix: condor_router_history doesn't handle exception for bad option  (By Timothy St. Clair )</td></tr>\n</tbody></table>", "type": "defect", "last_change": "2011-Jun-27 14:27", "status": "resolved", "created": "2011-Jun-13 16:44", "fixed_version": "2011-Jun-13 16:44", "broken_version": "", "priority": "3", "subsystem": "Tools", "assigned_to": "eje", "derived_from": "", "creator": "eje", "rust": "", "customer_group": "other", "visibility": "public", "notify": "eje@cs.wisc.edu, matt@cs.wisc.edu, tstclair@cs.wisc.edu, dan@hep.wisc.edu", "due_date": ""}