{"id": 4868, "title": "Ticket #4868: Assertion error in ShadowLog for CMS", "description": "<blockquote>\nWe're seeing ASSERTs in the <span class=\"wiki\"><a class=\"missing\" href=\"wiki?p=ShadowLog\" title=\"Shadow Log\">ShadowLog</a></span>; I think this is related to the error handling code for failures in delegateX509Proxy.\n\n<p></p><div class=\"verbatim\">\n<pre>02/05/15 11:08:55 (118013.14) (26660): Time to redelegate short-lived proxy to starter.\n02/05/15 11:09:26 (118013.14) (26660): CCBClient: Failed to read response from CCB server collector 128.142.141.24:9992 when requesting reversed connection to &lt;131.225.189.38:40006&gt;\n02/05/15 11:09:26 (118013.14) (26660): CCBClient: received failure message from CCB server collector 128.142.141.17:9992 in response to request for reversed connection to &lt;131.225.189.38:40006&gt;: CCB server rejecting request for ccbid 116562 because no daemon is currently registered with that id (perhaps it recently disconnected).\n02/05/15 11:09:26 (118013.14) (26660): Failed to reverse connect to &lt;131.225.189.38:40006&gt; via CCB.\n02/05/15 11:09:26 (118013.14) (26660): DCStarter::delegateX509Proxy: Failed to connect to starter &lt;131.225.189.38:40006?CCBID=128.142.141.17:9992#116562%20128.142.141.24:9992#113044&amp;noUDP&gt;\n02/05/15 11:09:27 (118013.14) (26660): CCBClient: received failure message from CCB server collector 128.142.141.24:9992 in response to request for reversed connection to &lt;131.225.189.38:40006&gt;: CCB server rejecting request for ccbid 113044 because no daemon is currently registered with that id (perhaps it recently disconnected).\n02/05/15 11:09:27 (118013.14) (26660): CCBClient: received failure message from CCB server collector 128.142.141.17:9992 in response to request for reversed connection to &lt;131.225.189.38:40006&gt;: CCB server rejecting request for ccbid 116562 because no daemon is currently registered with that id (perhaps it recently disconnected).\n02/05/15 11:09:27 (118013.14) (26660): Failed to reverse connect to &lt;131.225.189.38:40006&gt; via CCB.\n02/05/15 11:09:27 (118013.14) (26660): DCStarter::updateX509Proxy: Failed to connect to starter &lt;131.225.189.38:40006?CCBID=128.142.141.17:9992#116562%20128.142.141.24:9992#113044&amp;noUDP&gt;\n02/05/15 11:09:27 (118013.14) (26660): condor_write(): Socket closed when trying to write 29 bytes to startd glidein_37453_44612850@cmswn2091.fnal.gov, fd is 7\n02/05/15 11:09:27 (118013.14) (26660): Buf::write(): condor_write() failed\n02/05/15 11:09:27 (118013.14) (26660): ERROR \"Assertion ERROR on (result)\" at line 276 in file /slots/03/dir_59220/userdir/src/condor_shadow.V6.1/NTreceivers.cpp\n</pre></div>\n\n\n<p>I suspect there's a more appropriate error code to use and not an exception.  It's not clear a failure in delegation should kill the shadow.</p></blockquote>", "remarks": "<blockquote>\n</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "", "type": "incident", "last_change": "2015-Feb-05 19:30", "status": "new", "created": "2015-Feb-05 12:49", "fixed_version": "2015-Feb-05 12:49", "broken_version": "", "priority": "3", "subsystem": "DaemonsExecNode", "assigned_to": "", "derived_from": "#4490", "creator": "bbockelm", "rust": "", "customer_group": "cms", "visibility": "public", "notify": "", "due_date": ""}