{"id": 5359, "title": "Ticket #5359: Python functions broken after linking changes", "description": "<blockquote>\nCMS noticed that the ability to register python classad functions from within daemons is currently broken.\n\n<p>Playing with the linker (set LD_DEBUG=all in the environment), it appears that when python modules are loaded by the interpreter, they are loaded in the global scope.  Unfortunately, the python library (libpython2.6 in the case of RHEL6) is loaded in a private scope by the classads library (I think this is caused by the fix to <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=4998\" onclick=\"get_ticket_and_populate_wrapper('4998'); return false;\" title=\"condor_shadow segfaults on exit\">#4998</a></span>).\n\n</p><p>I <em>think</em> this can be solved by dlopen'ing the correct libpython2.6 from libclassad_python_user.so as RTLD_GLOBAL.  This should be fine because, as we found in <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=3407\" onclick=\"get_ticket_and_populate_wrapper('3407'); return false;\" title=\"HTCondor Python Bindings\">#3407</a></span>, the only conflicting symbol between python and condor is dprintf (which was fixed in that ticket as well).</p></blockquote>", "remarks": "<blockquote>\n<em>2015-Nov-10 11:24:59 by tannenba:</em> <br/>\n\nChanged to priority 2 and added it to the CMS parent ticket, as this is a blocker for CRAB3 at the Fermilab LPC as things are currently implemented at the CERN job router.  The python callout simply looks at a disk file of users (about 1k users) and decides if a route should happen. But  a work-around would be for the job router to simply read the route from disk and use a <span class=\"wiki\"><a class=\"missing\" href=\"wiki?p=ClassAd\" title=\"Class Ad\">ClassAd</a></span> list with ismember() function.\n\n<p></p><hr/>\n<em>2016-Jan-29 22:40:40 by bbockelm:</em> <br/>\n\nI now think this may be a misconfiguration on the CERN side.  I wasn't able to replicate locally.\n\n<p>However, I did find it was really hard to debug failures: I pushed a small fix to improve the debug messages.\n\n</p><p></p><hr/>\n<em>2016-Jan-29 22:50:25 by bbockelm:</em> <br/>\n\nTesting both on dev schedd (PROPER build) and an idle CERN schedd (UW build), it appears both work.</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody><tr><td align=\"right\" valign=\"top\" width=\"160\">2016-Jan-29 22:39</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"chngview?cn=47527\">[47527]</a></span>: Log the classad error message in the debug line. <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=5359\" onclick=\"get_ticket_and_populate_wrapper('5359'); return false;\" title=\"Python functions broken after linking changes\">#5359</a></span>  (By Brian Bockelman )</td></tr>\n</tbody></table>", "type": "defect", "last_change": "2016-Jan-30 19:07", "status": "resolved", "created": "2015-Nov-02 11:49", "fixed_version": "2015-Nov-02 11:49", "broken_version": "v080305", "priority": "2", "subsystem": "ClassAd", "assigned_to": "bbockelm", "derived_from": "#4490", "creator": "bbockelm", "rust": "", "customer_group": "cms", "visibility": "public", "notify": "letts@physics.ucsd.edu tannenba@cs.wisc.edu", "due_date": ""}