{"id": 5521, "title": "Ticket #5521: Failure during file transfer causing user data loss", "description": "<blockquote>\nMats Rynge from Pegasus reports a recurring failure where network problems can cause the loss of output data of completed jobs. Based on provided logs, we believe the following sequence of events is occurring. Everything here is from the point of view of the shadow.\n\n<p></p><ul>\n<li>Job runs, completes, and output transfer begins\n</li><li>After a long pause, the primary connection between shadow and starter fails\n</li><li>Shadow successfully reconnects to starter\n</li><li>Starter attempts new output transfer\n</li><li>Shadow EXCEPTs, as the previous transfer is still active (child process is still alive, is not cleaned up when shadow exits)\n</li><li>Job is rescheduled on another claim in a new shadow process\n</li><li>Job terminates and output transfer finishes in new shadow\n</li><li>Network connection in original (now orphaned) file transfer child process fails\n</li><li>Child process writes 0 bytes to file it was trying to receive at time of failure, truncating it\n</li></ul>\n\n<p>Two relatively simple changes should avoid this problem:\n</p><ul>\n<li>Shadow should kill file transfer process on a disconnect.\n</li><li>Schedd should track process family of shadow and clean it up when the shadow exits.</li></ul>\n</blockquote>", "remarks": "<blockquote>\n</blockquote>", "derived_tickets": "", "attachments": "<html><head></head><body></body></html>", "check_ins": "", "type": "defect", "last_change": "2016-Feb-18 14:22", "status": "new", "created": "2016-Feb-18 14:22", "fixed_version": "2016-Feb-18 14:22", "broken_version": "v080400", "priority": "4", "subsystem": "DaemonsSubmitNode", "assigned_to": "", "derived_from": "", "creator": "jfrey", "rust": "a29600", "customer_group": "other", "visibility": "public", "notify": "jfrey@cs.wisc.edu,rynge@isi.edu", "due_date": ""}