{"id": 448, "title": "Ticket #448: Create_Process's error messages are unhelpful", "description": "<blockquote>\nI stumbled across this error in Condor:\n<div class=\"verbatim\">\n<pre>05/01 03:03:54 Found idle scheduler universe job 112.0\n05/01 03:03:54 Job prep for 112.0 will not block, calling aboutToSpawnJobHandler\n() directly\n05/01 03:03:54 aboutToSpawnJobHandler() completed for job 112.0\n05/01 03:03:54 Starting sched universe job 112.0\n05/01 03:03:54 Create_Process: using fast clone() to create child process.\n05/01 03:03:54 Create_Process: child failed with errno 2 (No such file or direct\nory) before exec()\n05/01 03:03:54 Create_Process problems!\n</pre></div>\n\n\n<p>Notice it doesn't tell you what thing it was trying to exec? The fix is simple, add the requisite information into the output for the executable it was trying to use.</p></blockquote>", "remarks": "<blockquote>\n<em>2009-May-01 15:43:33 by psilord:</em> <br/>\n\nFixed the code on V7_2-branch, merged into master.</blockquote>", "derived_tickets": "", "attachments": "<html><head></head><body></body></html>", "check_ins": "", "type": "defect", "last_change": "2010-Jan-31 13:15", "status": "resolved", "created": "2009-May-01 11:35", "fixed_version": "2009-May-01 11:35", "broken_version": "", "priority": "3", "subsystem": "Daemons", "assigned_to": "psilord", "derived_from": "", "creator": "psilord", "rust": "", "customer_group": "other", "visibility": "public", "notify": "", "due_date": ""}